/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Proyecto2Operativos;
import static Clases.Proyecto2Operativos.main;
import javax.swing.JOptionPane;


/**
 *
 * @author kevin
 */
public class Interfaz extends javax.swing.JFrame {


   


    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ColaKevin3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ColaKevin1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ColaKevin2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        ColaRefuerzo = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ColaDiego1 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        ColaDiego2 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        ColaDiego3 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Ganador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ColaRefDiego = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        textoAI = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        textoAI2 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CambiarTiempo1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        Estudio1Pelea = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        Estudio2Pelea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("COLA PRIORIDAD 3 ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/58f37720a4fa116215a9240f (3).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 210, 80));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                                    HBO MAX VZLA + ");
        jLabel1.setNextFocusableComponent(jLabel1);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        ColaKevin3.setEditable(false);
        ColaKevin3.setColumns(20);
        ColaKevin3.setRows(5);
        jScrollPane1.setViewportView(ColaKevin3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 230, 120));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("COLA PRIORIDAD 1 ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 183, -1, -1));

        ColaKevin1.setEditable(false);
        ColaKevin1.setColumns(20);
        ColaKevin1.setRows(5);
        jScrollPane2.setViewportView(ColaKevin1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 230, 230, 120));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("COLA PRIORIDAD 2 ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        ColaKevin2.setEditable(false);
        ColaKevin2.setColumns(20);
        ColaKevin2.setRows(5);
        jScrollPane3.setViewportView(ColaKevin2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 230, 120));

        ColaRefuerzo.setEditable(false);
        ColaRefuerzo.setColumns(20);
        ColaRefuerzo.setRows(5);
        jScrollPane4.setViewportView(ColaRefuerzo);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 230, 120));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("COLA DE REFUERZO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("ESTUDIO 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        ColaDiego1.setEditable(false);
        ColaDiego1.setColumns(20);
        ColaDiego1.setRows(5);
        jScrollPane6.setViewportView(ColaDiego1);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 250, 140));

        ColaDiego2.setEditable(false);
        ColaDiego2.setColumns(20);
        ColaDiego2.setRows(5);
        jScrollPane7.setViewportView(ColaDiego2);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 210, 250, 140));

        ColaDiego3.setEditable(false);
        ColaDiego3.setColumns(20);
        ColaDiego3.setRows(5);
        jScrollPane8.setViewportView(ColaDiego3);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 250, 130));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("ESTUDIO 2");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("COLA PRIORIDAD 1 ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("COLA PRIORIDAD 2 ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("COLA DE REFUERZO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, -1, -1));

        jLabel13.setText("Cambiar Velocidad");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, -1, -1));

        Ganador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GanadorActionPerformed(evt);
            }
        });
        getContentPane().add(Ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 760, 210, -1));

        jButton1.setText("Cambiar!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rick-And-Morty-PNG-Images-HD (1).png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 310, 420));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("COLA PRIORIDAD 3 ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, -1, -1));

        ColaRefDiego.setEditable(false);
        ColaRefDiego.setColumns(20);
        ColaRefDiego.setRows(5);
        jScrollPane9.setViewportView(ColaRefDiego);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 410, 250, 130));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("AI revisando ID: ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        textoAI.setEditable(false);
        textoAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAIActionPerformed(evt);
            }
        });
        getContentPane().add(textoAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 60, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Capitulo Estudio 1");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, -1, -1));

        textoAI2.setEditable(false);
        textoAI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAI2ActionPerformed(evt);
            }
        });
        getContentPane().add(textoAI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 570, 60, 40));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Ganador:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 710, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("AI revisando ID: ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Capitulo Estudio 2");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, -1, -1));

        CambiarTiempo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarTiempo1ActionPerformed(evt);
            }
        });
        getContentPane().add(CambiarTiempo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 80, -1));

        Estudio1Pelea.setColumns(20);
        Estudio1Pelea.setRows(5);
        jScrollPane5.setViewportView(Estudio1Pelea);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 280, 160));

        Estudio2Pelea.setColumns(20);
        Estudio2Pelea.setRows(5);
        jScrollPane10.setViewportView(Estudio2Pelea);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 680, 270, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GanadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GanadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try{
            String answer = CambiarTiempo1.getText();
            int option = Integer.parseInt(answer);
            Proyecto2Operativos.tiempo = option; 
            
       }catch (Exception e){
            JOptionPane.showMessageDialog(null,"No es una opcion valida");
            
    }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textoAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAIActionPerformed

    private void textoAI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAI2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAI2ActionPerformed

    private void CambiarTiempo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarTiempo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CambiarTiempo1ActionPerformed
    
    public void setTextColaKevin1(String text){
        ColaKevin1.setText(text);
    }
    
    public void setTextColaKevin2(String text){
        ColaKevin2.setText(text);
    }
    public void setTextColaKevin3(String text){
        ColaKevin3.setText(text);
    }
     public void setTextColaKevin4(String text){
        ColaRefuerzo.setText(text);
    }
    
    public void setTextColaDiego1(String text){
        ColaDiego1.setText(text);
    }
    
    public void setTextColaDiego2(String text){
        ColaDiego2.setText(text);
    }
    
    public void setTextColaDiego3(String text){
        ColaDiego3.setText(text);
    }
    
    public void setTextColaDiego4(String text){
        ColaRefDiego.setText(text);
    }
    public void setidDiego(String text){
       textoAI2.setText(text);
    }
    
       public void setidKevin(String text){
        textoAI.setText(text);

    }
        public void setDiegoPelea(String text){
        Estudio2Pelea.setText(text);
    }
        public void setKevinPelea(String text){
        Estudio1Pelea.setText(text);
    }
        
        public void setGanador(String text){
        Ganador.setText(text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CambiarTiempo1;
    private javax.swing.JTextArea ColaDiego1;
    private javax.swing.JTextArea ColaDiego2;
    private javax.swing.JTextArea ColaDiego3;
    private javax.swing.JTextArea ColaKevin1;
    private javax.swing.JTextArea ColaKevin2;
    private javax.swing.JTextArea ColaKevin3;
    private javax.swing.JTextArea ColaRefDiego;
    private javax.swing.JTextArea ColaRefuerzo;
    private javax.swing.JTextArea Estudio1Pelea;
    private javax.swing.JTextArea Estudio2Pelea;
    private javax.swing.JTextField Ganador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField textoAI;
    private javax.swing.JTextField textoAI2;
    // End of variables declaration//GEN-END:variables
}
